# Generated by Django 4.2.7 on 2025-09-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_type', models.CharField(choices=[('video', 'Video Consultation'), ('in_person', 'In-Person Visit')], default='video', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('no_show', 'No Show'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('reason', models.TextField(help_text='Reason for consultation')),
                ('symptoms', models.TextField(blank=True)),
                ('medical_history', models.TextField(blank=True)),
                ('video_room_id', models.CharField(blank=True, max_length=255)),
                ('video_join_token', models.TextField(blank=True)),
                ('video_join_token_expires', models.DateTimeField(blank=True, null=True)),
                ('consultation_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=255)),
                ('scheduled_at', models.DateTimeField()),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('doctor_notes', models.TextField(blank=True)),
                ('patient_feedback', models.TextField(blank=True)),
                ('requires_follow_up', models.BooleanField(default=False)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'appointments_appt',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='AppointmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('booking_confirmation', 'Booking Confirmation'), ('24_hour', '24 Hour Reminder'), ('1_hour', '1 Hour Reminder'), ('15_minute', '15 Minute Reminder'), ('post_visit', 'Post-Visit Follow-up')], max_length=20)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push Notification')], max_length=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_status', models.CharField(default='pending', max_length=20)),
                ('delivery_id', models.CharField(blank=True, max_length=255)),
                ('message_content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appointment Reminder',
                'verbose_name_plural': 'Appointment Reminders',
                'db_table': 'appointments_reminder',
            },
        ),
        migrations.CreateModel(
            name='AppointmentReschedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Appointment Reschedule',
                'verbose_name_plural': 'Appointment Reschedules',
                'db_table': 'appointments_reschedule',
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('booked', 'Booked'), ('blocked', 'Blocked')], default='open', max_length=10)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule Slot',
                'verbose_name_plural': 'Schedule Slots',
                'db_table': 'schedule_slot',
            },
        ),
    ]
