# Generated by Django 4.2.7 on 2025-09-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleslot',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_slots', to='doctors.doctor'),
        ),
        migrations.AddField(
            model_name='appointmentreschedule',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reschedules', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointmentreschedule',
            name='new_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_reschedules', to='appointments.scheduleslot'),
        ),
        migrations.AddField(
            model_name='appointmentreschedule',
            name='old_slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_reschedules', to='appointments.scheduleslot'),
        ),
    ]
