# Generated by Django 4.2.7 on 2025-09-05 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emr', '0002_initial'),
    ]

    operations = [
    ]
