# Generated by Django 4.2.7 on 2025-09-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
        ('doctors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refund',
            name='processed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processed_refunds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='appointments',
            field=models.ManyToManyField(related_name='payouts', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='doctorpayout',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='doctors.doctor'),
        ),
    ]
