# Generated by Django 4.2.7 on 2025-09-04 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RTCJoinToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=500)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'RTC Join Token',
                'verbose_name_plural': 'RTC Join Tokens',
                'db_table': 'rtc_join_token',
            },
        ),
        migrations.CreateModel(
            name='RTCRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('created', 'Created'), ('active', 'Active'), ('ended', 'Ended'), ('expired', 'Expired')], default='created', max_length=20)),
                ('max_participants', models.PositiveIntegerField(default=2)),
                ('recording_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'RTC Room',
                'verbose_name_plural': 'RTC Rooms',
                'db_table': 'rtc_room',
            },
        ),
        migrations.CreateModel(
            name='RTCSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_type', models.CharField(choices=[('offer', 'Offer'), ('answer', 'Answer'), ('ice_candidate', 'ICE Candidate'), ('join', 'Join'), ('leave', 'Leave')], max_length=20)),
                ('payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='rtc.rtcroom')),
            ],
            options={
                'verbose_name': 'RTC Signal',
                'verbose_name_plural': 'RTC Signals',
                'db_table': 'rtc_signals',
                'ordering': ['-created_at'],
            },
        ),
    ]
