# Generated by Django 4.2.7 on 2025-09-04 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rtc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rtcsignal',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtc_signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rtcroom',
            name='appointment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rtc_room', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='rtcjointoken',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_tokens', to='rtc.rtcroom'),
        ),
        migrations.AddField(
            model_name='rtcjointoken',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rtc_join_tokens', to=settings.AUTH_USER_MODEL),
        ),
    ]
